site_name: База знаний
site_url: https://shlyapp.github.io/obsidian-knowledge-base/
repo_url: https://github.com/shlyapp/obsidian-knowledge-base
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: lime 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  custom_dir: overrides

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: simple/telegram
      link: https://t.me/selfdoor
    - icon: simple/github
      link: https://github.com/shlyapp
    - icon: simple/habr
      link: https://habr.com/ru/users/selfdoor/

plugins:
 - search
 - document-dates