site_name: База знаний
theme:
  name: material
  features:
    - navigation.path
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: lime 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  custom_dir: overrides

extra:
  social:
    - icon: simple/telegram
      link: https://t.me/selfdoor
    - icon: simple/github
      link: https://github.com/shlyapp
    - icon: simple/habr
      link: https://habr.com/ru/users/selfdoor/

plugins:
 - search
 - document-dates